# Generated by Django 3.2.5 on 2021-09-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationsUtilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_ip', models.CharField(max_length=1000)),
                ('valide', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('code_continent', models.CharField(max_length=10)),
                ('nom_continent', models.CharField(max_length=100)),
                ('code_pays', models.CharField(max_length=10)),
                ('nom_pays', models.CharField(max_length=100)),
                ('union_europeene', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=100)),
                ('zone_horaire', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse_mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('numero_tel', models.IntegerField()),
                ('annee_naissance', models.IntegerField()),
                ('localisation', models.CharField(max_length=1000)),
                ('adresse_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.informationsutilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Recherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_recherche', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.informationsutilisateurs')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateurs')),
                ('categorie_recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsSupprimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.informationsutilisateurs')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateurs')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produits')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsAjouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.informationsutilisateurs')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateurs')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produits')),
            ],
        ),
        migrations.CreateModel(
            name='PageVisiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.informationsutilisateurs')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_saisi', models.CharField(max_length=1000)),
                ('email_saisi', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('messages', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.informationsutilisateurs')),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='InfoConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_email', models.EmailField(max_length=254)),
                ('test_password', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.informationsutilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(null=True)),
                ('valide', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.utilisateurs')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1)),
                ('prix', models.IntegerField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateurs.commande')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produits')),
            ],
        ),
    ]
