# Generated by Django 3.2.5 on 2021-09-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_article_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='nom',
        ),
    ]
