# Generated by Django 3.2.5 on 2021-09-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0005_remove_recherche_categorie_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.IntegerField(default=0),
        ),
    ]
