# Generated by Django 3.2.5 on 2021-09-19 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image_couverture', models.ImageField(upload_to='images_couvertures/')),
            ],
        ),
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produit', models.CharField(max_length=90)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('reduction', models.IntegerField(blank=True, null=True)),
                ('quantite', models.IntegerField()),
                ('photo1', models.ImageField(upload_to='images_produits/')),
                ('photo2', models.ImageField(upload_to='images_produits/')),
                ('photo3', models.ImageField(upload_to='images_produits/')),
                ('photo4', models.ImageField(upload_to='images_produits/')),
                ('photo5', models.ImageField(upload_to='images_produits/')),
                ('nom_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='SuperCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('image_couverture', models.ImageField(upload_to='images_couvertures/')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitsSuper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_promo', models.IntegerField()),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produits')),
                ('supercategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.supercategorie')),
            ],
        ),
    ]
